const Database = require('better-sqlite3');
const db = new Database('E:/vertex/data/backspace.db');
const tables = db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all().map((r) => r.name);
console.log('all tables:', tables.join(', '));
console.log('has staff_roles:', tables.includes('staff_roles'));
console.log('has moderation_events:', tables.includes('moderation_events'));
console.log('has audit_log:', tables.includes('audit_log'));
const idx = db.prepare("SELECT name FROM sqlite_master WHERE type='index' AND name IN ('idx_moderation_events_user_id','idx_moderation_events_created_at','idx_audit_log_created_at','idx_audit_log_action')").all().map((r) => r.name);
console.log('expected indexes present:', idx.join(', '));
console.log('pending FK columns ok:', ['netrex_enabled','netrex_expires_at','staff_role','last_seen_at','banned_until','ban_reason','banned_at','banned_by'].map((c) => db.prepare('PRAGMA table_info(users)').all().some((x) => x.name === c) ? c : `MISSING:${c}`).join(', '));
db.close();